/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.JOptionPane;enum ComboTextValues {
    comboText, comboText1, comboText2;
}

enum ButtonValues {
    button, button1, button2
}

enum LabelValues {
    label, label1, label2
}
public class myComponent extends javax.swing.JPanel {

    /**
     * Creates new form myComponent
     */
    public myComponent() {
        initComponents();
        String[] lines = {"1.", "2.","3.","4."};
        setComboBoxText(lines);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        jLabel1.setText("Hi World");

        jButton1.setText("Check 1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel1)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jButton1)
                .addContainerGap(62, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       showInfo("Button");
    }//GEN-LAST:event_jButton1ActionPerformed

     private void showInfo(String pressed) {
        JOptionPane.showMessageDialog(this, "Selected items index = " + jComboBox1.getSelectedIndex() + "\n" + pressed + " pressed");
        jButton1.setVisible(true);
    }
     
     public void setComboBoxText(String[] lines) {
        jComboBox1.removeAllItems();
        for (String line : lines) {
            jComboBox1.addItem(line);
        }
    }
     LabelValues labels;

    public void setjLabel(LabelValues labels) {
        this.labels = labels;
        switch (labels) {
            //"Нажми", "Нажми кнопку", "press button"
            case label:
                jLabel1.setText("Hi World");
                break;
            case label1:
                jLabel1.setText("Hello World");
                break;
            case label2:
                jLabel1.setText("Happy World");
                break;

        }
    }

    public LabelValues getjLabel() {
        return labels;
    }

    ButtonValues buttons;

    public void setjButton(ButtonValues buttons) {
        this.buttons = buttons;
        switch (buttons) {
            case button:
                jButton1.setText("Check 1");
                break;
            case button1:
                jButton1.setText("Check 2");
                break;
            case button2:
                jButton1.setText("Check 3");
                break;
        }
    }

    public ButtonValues getjButton() {
        return buttons;
    }

    ComboTextValues comboBoxes;

    public void setjComboBox(ComboTextValues comboBox) {
        this.comboBoxes = comboBox;
        switch (comboBoxes) {
            case comboText:
                setComboBoxText(new String[]{"1.", "2.", "3.","4."});
                break;
            case comboText1:
                setComboBoxText(new String[]{"a)", "b)", "c)", "d)"});
                break;
            case comboText2:
                setComboBoxText(new String[]{"a.", "b.", "c.", "d."});
                break;
        }
    }

    public ComboTextValues getjComboBox() {
        return comboBoxes;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
